### ISSUE TITLE
Jovo load doesn't create src files

### ISSUE THREAD

**Issue by dustincoates** [jovotech/jovo-component-get-phone-number#4]
## Steps to Reproduce

Install via:
```
$ npm install jovo-component-get-phone-number --save
```

Load via:
```
$ jovo load jovo-component-get-phone-number
```

After these two steps, this is the created file structure:
```
src/
└── components/
    jovo-component-get-phone-number/
        └── models/
        └── README.md
```

Node version: 12.14.0
Jovo CLI version: 3.0.18
Jovo framework version: 3.0.19

**Comment by aswetlow** [comment]
Weird, I can't reproduce. `src` was created and has files.

what's in your `node_modules/jovo-component-get-phone-number` ?

**Comment by dustincoates** [comment]
It's a Typescript Jovo project.

The node module looks alright:

![Screenshot from 2020-08-03 19-07-08](https://user-images.githubusercontent.com/1909592/89208535-da39a400-d5bc-11ea-9010-7f03e1ca59dd.png)

**Comment by aswetlow** [comment]
Could you try it in a new empty project? Just to make sure it persits.
I couldn't reproduce it with Typescript projects either :/

**Comment by dustincoates** [comment]
Worked on the empty project.

On the first project, I uninstalled the node module, reinstalled it, then ran Jovo load again. Same result.

**Comment by aswetlow** [comment]
Could you delete `/node_modules` and `package-lock.json` ? We had issues with that file 😄

**Comment by dustincoates** [comment]
Still not, which makes sense, as the module had all of the correct files. Very strange.

**Comment by dustincoates** [comment]
@aswetlow sorry, I was actually mistaken before--I just tried it again with a new project, but this time specified it to be a Typescript project (forgot to before) and it didn't work this time for the new project, either.

Taking a look at the CLI code, I wonder if it's this block: https://github.com/jovotech/jovo-cli/blob/f71805efed5c803234aa37eefb5a9d40b145a5d4/jovo-cli/src/commands/load.ts#L112:L118

Just at first glance, it appears to skip over everything in the `dist` directory, but that's all that is installed in the node module dir.

**Comment by dustincoates** [comment]
@aswetlow do you have any suggestions on best way to handle this? I tried doing it manually, but I'm running into issues and afraid of going down a rabbit hole.

**Comment by aswetlow** [comment]
Since I can't reproduce, I don't have an advice here :/ 

We're, especially @rubenaeg, is looking into it. Thanks for the patience.

**Comment by dustincoates** [comment]
All good, thanks @aswetlow

**Comment by rubenaeg** [comment]
Hey @dustincoates , I think I know what the problem is, the component is missing the TypeScript files which `jovo load` should copy into your `src/` folder, so skipping `dist/` is by design, it's just that the correct files are missing... I think I can publish a fix tomorrow! Thank you for your patience.

**Comment by dustincoates** [comment]
Hi @rubenaeg do you know when you'll push those changes? :pray:

**Comment by dustincoates** [comment]
Hey @rubenaeg @aswetlow, we've decided to go with another approach so this is no longer a necessity for us. Looking forward to trying it out in the future if we need it.
